// generated by Fast Light User Interface Designer (fluid) version 1.0300

// $Header: /p/course/cs559-gleicher/private/CVS/GrTown/GraphicsTownUI.fl,v 1.4 2008/11/14 19:53:30 gleicher Exp $
// Note: this user interface (.cxx and .h) was created
// automatically by running fluid on the ".fl" file
// you should not edit the .cxx or .h file!

// Use "fluid" to edit the UI interactively
// CS559 Graphics Town
#include "GrTown_PCH.H"
#include "GraphicsTownUI.H"
#include "GrObject.H"
#include "GrWorld.H"
using std::vector;

void GraphicsTownUI::cb_pickCamera_i(Fl_Browser*, void*) {
  pickInteresting->deselect();
}
void GraphicsTownUI::cb_pickCamera(Fl_Browser* o, void* v) {
  ((GraphicsTownUI*)(o->parent()->parent()->user_data()))->cb_pickCamera_i(o,v);
}

void GraphicsTownUI::cb_time_i(Fl_Value_Slider*, void*) {
  townView->damage(1);
}
void GraphicsTownUI::cb_time(Fl_Value_Slider* o, void* v) {
  ((GraphicsTownUI*)(o->parent()->parent()->user_data()))->cb_time_i(o,v);
}

void GraphicsTownUI::cb_fov_i(Fl_Value_Slider*, void*) {
  townView->damage(1);
}
void GraphicsTownUI::cb_fov(Fl_Value_Slider* o, void* v) {
  ((GraphicsTownUI*)(o->parent()->parent()->user_data()))->cb_fov_i(o,v);
}

void GraphicsTownUI::cb_pickInteresting_i(Fl_Browser*, void*) {
  pickCamera->deselect();
follower->value(0);
}
void GraphicsTownUI::cb_pickInteresting(Fl_Browser* o, void* v) {
  ((GraphicsTownUI*)(o->parent()->parent()->user_data()))->cb_pickInteresting_i(o,v);
}

void GraphicsTownUI::cb_Fly_i(Fl_Button*, void*) {
  follower->value(0);
pickCamera->deselect();
pickInteresting->deselect();
townView->damage(1);
}
void GraphicsTownUI::cb_Fly(Fl_Button* o, void* v) {
  ((GraphicsTownUI*)(o->parent()->parent()->user_data()))->cb_Fly_i(o,v);
}

Fl_Double_Window* GraphicsTownUI::make_window() {
  { window = new Fl_Double_Window(931, 616, "CS 559 Graphics Town!");
    window->labelsize(12);
    window->user_data((void*)(this));
    { TownViewWidget* o = townView = new TownViewWidget(5, 5, 760, 605);
      townView->box(FL_NO_BOX);
      townView->color(FL_BACKGROUND_COLOR);
      townView->selection_color(FL_BACKGROUND_COLOR);
      townView->labeltype(FL_NORMAL_LABEL);
      townView->labelfont(0);
      townView->labelsize(14);
      townView->labelcolor(FL_FOREGROUND_COLOR);
      townView->align(Fl_Align(FL_ALIGN_BOTTOM));
      townView->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(townView);
      o->ui = this;
    } // TownViewWidget* townView
    { Fl_Group* o = new Fl_Group(770, 5, 155, 600);
      { Fl_Browser* o = pickCamera = new Fl_Browser(770, 5, 155, 165, "view");
        pickCamera->type(2);
        pickCamera->callback((Fl_Callback*)cb_pickCamera);
        Fl_Group::current()->resizable(pickCamera);
        for(vector<GrObject*>::iterator g=theObjects.begin(); g != theObjects.end(); ++g)
        if((*g)->ridable) o->add((*g)->name.c_str(),*g);
      } // Fl_Browser* pickCamera
      { cull = new Fl_Button(770, 580, 75, 25, "Backface Cull");
        cull->type(1);
        cull->value(1);
        cull->selection_color((Fl_Color)11);
        cull->labelsize(12);
      } // Fl_Button* cull
      { time = new Fl_Value_Slider(780, 470, 115, 20, "Time of Day (24hr)");
        time->type(5);
        time->maximum(24);
        time->step(1);
        time->value(9);
        time->callback((Fl_Callback*)cb_time);
      } // Fl_Value_Slider* time
      { fov = new Fl_Value_Slider(905, 430, 15, 75, "FoV");
        fov->minimum(1);
        fov->maximum(180);
        fov->step(1);
        fov->value(45);
        fov->callback((Fl_Callback*)cb_fov);
      } // Fl_Value_Slider* fov
      { lgTex = new Fl_Button(850, 580, 75, 25, "textured ground");
        lgTex->type(1);
        lgTex->value(1);
        lgTex->selection_color((Fl_Color)11);
        lgTex->labelsize(10);
      } // Fl_Button* lgTex
      { follower = new Fl_Button(770, 190, 70, 25, "Follow");
        follower->type(1);
        follower->color(FL_DARK1);
        follower->selection_color((Fl_Color)11);
      } // Fl_Button* follower
      { rate = new Fl_Value_Output(875, 520, 50, 25, "frame rate");
        rate->maximum(100);
        rate->step(0.1);
      } // Fl_Value_Output* rate
      { speedup = new Fl_Value_Slider(840, 550, 85, 25, "speedup");
        speedup->type(1);
        speedup->maximum(3);
        speedup->step(0.2);
        speedup->value(1);
        speedup->align(Fl_Align(FL_ALIGN_LEFT));
      } // Fl_Value_Slider* speedup
      { Fl_Browser* o = pickInteresting = new Fl_Browser(770, 225, 155, 165, "sights");
        pickInteresting->type(2);
        pickInteresting->callback((Fl_Callback*)cb_pickInteresting);
        for(vector<GrObject*>::iterator g=theObjects.begin(); g != theObjects.end(); ++g)
        if((*g)->interesting) o->add((*g)->name.c_str(),*g);
      } // Fl_Browser* pickInteresting
      { Fl_Button* o = new Fl_Button(850, 190, 70, 25, "Fly");
        o->callback((Fl_Callback*)cb_Fly);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
  return window;
}
